version: '3.8'
services:
  db:
    image: mysql:8
    container_name: hapi-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hapi
      MYSQL_DATABASE: user
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie here'
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'
  api:
    build: api/.
    container_name: api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    command: dockerize -wait tcp://db:3306 -timeout 60s npm start
    depends_on:
      - db
      - rabbitmq

  consumer:
    build: mailer-service/.
    container_name: consumer
    volumes:
      - ./mailer-service:/app
      - /app/node_modules
    command: dockerize -wait tcp://db:3306 -timeout 60s npm start
    depends_on:
      - db
      - rabbitmq

